# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activation',
            old_name='string',
            new_name='unique_key',
        ),
    ]
