# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161016_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
