# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161017_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
