# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161018_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 30, 7, 52, 54, 416509, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changepassword',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 30, 7, 53, 3, 425038, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
