# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161030_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
