# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20161010_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='penalty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_level_score',
            field=models.IntegerField(default=40),
        ),
    ]
