# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20161010_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bonus_question_opened',
            field=models.BooleanField(default=False),
        ),
    ]
