# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_userinfo_bonus_question_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='current_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=1),
        ),
        migrations.AlterField(
            model_name='userlevelprogress',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=1),
        ),
    ]
