# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20161011_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.TextField(unique=True),
        ),
    ]
