# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20161011_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='current_level_opened_questions',
            field=models.IntegerField(default=0),
        ),
    ]
