# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_userinfo_current_level_opened_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
