# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20161016_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
